version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      monorepo-dependencies:
        group-by: dependency-name
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
