packages:
  - packages/**

allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true

minimumReleaseAgeExclude:
  - tsx@4.22.4
  - '@testing-library/user-event@14.6.3'
  - fastify@5.11.2
  - undici@8.10.0

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
