packages:
  - packages/**

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  axios@>=1.3.2 <=1.7.3: '>=1.7.4'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  ip@=2.0.0: '>=2.0.1'
  tar-fs@>=2.0.0 <2.1.2: '>=2.1.2'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tar@<6.2.1: '>=6.2.1'
